### ISSUE TITLE
Page load displays raw code

### ISSUE THREAD

**Issue by AmonBune** [nextcloud/tasks#242]
I'm using NC 15 and when I click on Tasks on the top bar, the page shows some garbled code stuff (they seem like codes from a template engine?) like in the following picture:
![image](https://user-images.githubusercontent.com/15927695/52055445-b7f63e80-255f-11e9-9013-65ca9b899273.png)

It would be nice if this text could be changed to something like "Tasks are being loaded..." or "Loading..." instead of this cryptic stuff.

**Comment by raimund-schluessler** [comment]
This is only showing up on app load, right?

This is because Angular.js is not loaded and does not fill the template yet. This is solved with the vue rewrite #194. Please reopen if I got it wrong.

**Comment by JLueke** [comment]
It doesn't show the template all the times but it still happens in like 1 of 4 times.

Nextcloud 15.0.5 Docker with Apache
Tasks 0.9.8

**Comment by raimund-schluessler** [comment]
> It doesn't show the template all the time but it still happens in like 1 of 4 times.

The fix will be included in Tasks 0.10.0. You can try the alpha version, if you like: #270

**Comment by clcain** [comment]
@raimund-schluessler Just wanted to say thanks for fixing this on version v0.10.0! It makes the whole app experience a lot nicer.
