### ISSUE TITLE
Task list sharing search field does not find existing users or groups

### ISSUE THREAD

**Issue by TheRedScreen64** [nextcloud/tasks#2970]
### Steps to reproduce

1. Open Tasks app on nextcloud
2. Click on the button for sharing a list
3. Search for an existing user or group in the text field that popped up
4. It does not return any results, even though they do exist

### Expected behavior

The search field should display matching users or groups that exist on the server, allowing the task list to be shared with them.

### Actual behaviour

No users or groups are found, even though they exist.

### Tasks app version

0.17.0

### CalDAV-clients used

None

### Browser

Firefox 144.0

### Client operating system

Windows

### Server operating system

Linux

### Web server

Docker image

### Nextcloud version

32.0.1

### Updated from an older installed version or fresh install

Updated from an older version

### Browser log

```Text
When searching for "Family" group:
[vue-select warn]: Label key "option.label" does not exist in options object {"user":"Family","displayName":"Family","icon":"icon-group","uri":"principal:principals/groups/Family","isGroup":true,"isCircle":false,"isNoUser":true,"search":"Family"}.
https://vue-select.org/api/props.html#getoptionlabel

When searching for "SomeUser" (username redacted here):
[vue-select warn]: Label key "option.label" does not exist in options object {"user":"","displayName":"SomeUser","icon":"icon-user","uri":"principal:principals/users/SomeUser","isGroup":false,"isCircle":false,"isNoUser":false,"search":"SomeUser"}.
https://vue-select.org/api/props.html#getoptionlabel
```

When searching for a non existing user, as expected, no log is printed.
So my guess is it does find the user/group, but can't display them for some reason.

**Comment by stanlog** [comment]
Hello, same behavior here. I can't share new tasks with my working groups. Complicated to work together :) Do you know when the new version of the app will be available ?

**Comment by ardarandir** [comment]
Same here. Very annoying. Couldnt find a workaround to create a shared task list - any advice?

**Comment by raimund-schluessler** [comment]
Fixed with 0.17.1 which was just released.

**Comment by FrameXX** [comment]
I have Tasks 0.18.1 and NextCloud 34.0.3 and I am still facing this issue. I have defined user groups I am admin of, but the share popup cannot find anything.

EDIT: I was able to share the task lists via the calendar app.
